### ISSUE TITLE
Dropbox 관련 기능 추가

### ISSUE THREAD

**Issue by rlatmfrl24** [Applemint-soulkey/applemint-next#9]
### 적용범위
  - `imgur.com`
 
### Process
  1. Crawl시 해당 도메인 예외처리
  2. 적용 도메인 URL -> `imageQueue` Collection으로 보냄
  3. imageQueue Trigger에서 각 도메인별 처리 로직으로 Direct Link 추출
  4. 추출된 Direct Link는 'gallery' Collection으로 보냄
  5. Front-end에는 별도로 Gallery View 생성
  6. Gallery View는 Dropbox 연동 버튼 적용 및 CRUD UI 적용

### Todo
  - [x] Dropbox 기본 버튼 사용 가능 여부 확인
  - [x] Gallery Column 라인 조절 기능 추가
  - [x] 사진 클릭시 팝업으로 확대 화면 추가
  - [x] 삭제/Dropbox/Keep/Bookmark 기능 추가
  - [x] 삭제 및 Dropbox 기능 수행시 사용자가 확인가능한 Snack 추가

**Comment by rlatmfrl24** [comment]
진행중 작업
- ~Trigger에서 Direct 링크를 구분하지 못함~
- ~imgur 링크가 아닌 Direct 링크 적용되는지 확인~
- ~imgur 링크와 imgur Direct 링크를 구분하는 로직 필요~
- ~링크 삽입 완료되면 imageQueue 삭제하도록 로직 적용 필요~ -> #14 로 이동

**Comment by rlatmfrl24** [comment]
resolved
